In [2]:
from gymjsp.jsspenv import HeuristicJsspEnv
from tianshou.env import SubprocVectorEnv
import numpy as np
import random
import torch
import warnings
warnings.filterwarnings('ignore')

In [4]:
def helper_function():
  env = HeuristicJsspEnv("ft06")
  return env

env = HeuristicJsspEnv("ft06")
train_envs = SubprocVectorEnv([helper_function for _ in range(5)])

In [13]:
[action_space.sample() for action_space in train_envs.action_space]

[3, 1, 0, 2, 2]

In [17]:
train_envs.step([0,1,2,3,2])

(array([[ 0. ,  0. ,  1. , ...,  0. ,  0. ,  0.5],
        [ 0. ,  0. , -1. , ...,  0. ,  0. ,  0.5],
        [ 0. ,  0. , -1. , ...,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  1. , ...,  0. ,  0. ,  0.5],
        [ 0. ,  0. , -1. , ...,  0. ,  0. ,  0.5]], dtype=float32),
 array([-0.66666667, -0.5       , -0.66666667, -0.41666667, -0.66666667]),
 array([False, False, False, False, False]),
 array([{'cost': 0, 'wait': 0, 'total action': 4, 'makespan': 4, 'env_id': 0},
        {'cost': 0, 'wait': 0, 'total action': 4, 'makespan': 4, 'env_id': 1},
        {'cost': 0, 'wait': 0, 'total action': 4, 'makespan': 4, 'env_id': 2},
        {'cost': 0, 'wait': 0, 'total action': 4, 'makespan': 4, 'env_id': 3},
        {'cost': 0, 'wait': 0, 'total action': 4, 'makespan': 4, 'env_id': 4}],
       dtype=object))